// Generated by https://quicktype.io

export interface Episodio {
  id:       number;
  url:      string;
  name:     string;
  season:   number;
  number:   number;
  type:     EpisodioType;
  airdate:  string;
  airtime:  string;
  airstamp: string;
  runtime:  number;
  rating:   Rating;
  image:    Image | null;
  summary:  null | string;
  show:     Show;
  _links:   EpisodioLinks;
}

export interface EpisodioLinks {
  self: Self;
  show: Self;
}

export interface Self {
  href: string;
}

export interface Image {
  medium:   string;
  original: string;
}

export interface Rating {
  average: number | null;
}

export interface Show {
  id:             number;
  url:            string;
  name:           string;
  type:           ShowType;
  language:       Language;
  genres:         string[];
  status:         Status;
  runtime:        number | null;
  averageRuntime: number;
  premiered:      string;
  ended:          null | string;
  officialSite:   null | string;
  schedule:       Schedule;
  rating:         Rating;
  weight:         number;
  network:        Network | null;
  webChannel:     Network | null;
  dvdCountry:     null;
  externals:      Externals;
  image:          Image;
  summary:        string;
  updated:        number;
  _links:         ShowLinks;
}

export interface ShowLinks {
  self:            Self;
  previousepisode: Self;
  nextepisode?:    Self;
}

export interface Externals {
  tvrage:  number | null;
  thetvdb: number | null;
  imdb:    null | string;
}

export enum Language {
  English = "English",
  Spanish = "Spanish",
}

export interface Network {
  id:           number;
  name:         string;
  country:      Country;
  officialSite: null | string;
}

export interface Country {
  name:     Name;
  code:     Code;
  timezone: Timezone;
}

export enum Code {
  Kr = "KR",
  Us = "US",
}

export enum Name {
  KoreaRepublicOf = "Korea, Republic of",
  UnitedStates = "United States",
}

export enum Timezone {
  AmericaNewYork = "America/New_York",
  AsiaSeoul = "Asia/Seoul",
}

export interface Schedule {
  time: string;
  days: Day[];
}

export enum Day {
  Friday = "Friday",
  Monday = "Monday",
  Saturday = "Saturday",
  Sunday = "Sunday",
  Thursday = "Thursday",
  Tuesday = "Tuesday",
  Wednesday = "Wednesday",
}

export enum Status {
  Ended = "Ended",
  Running = "Running",
  ToBeDetermined = "To Be Determined",
}

export enum ShowType {
  Animation = "Animation",
  Documentary = "Documentary",
  GameShow = "Game Show",
  News = "News",
  Reality = "Reality",
  Scripted = "Scripted",
  Sports = "Sports",
  TalkShow = "Talk Show",
  Variety = "Variety",
}

export enum EpisodioType {
  Regular = "regular",
}
