// Generated by https://quicktype.io

export interface Programa {
  id:             number;
  url:            string;
  name:           string;
  type:           string;
  language:       string;
  genres:         any[];
  status:         string;
  runtime:        null;
  averageRuntime: null;
  premiered:      string;
  ended:          null;
  officialSite:   string;
  schedule:       Schedule;
  rating:         Rating;
  weight:         number;
  network:        null;
  webChannel:     WebChannel;
  dvdCountry:     null;
  externals:      Externals;
  image:          Image;
  summary:        string;
  updated:        number;
  _links:         Links;
}

export interface Links {
  self:            Nextepisode;
  previousepisode: Nextepisode;
  nextepisode:     Nextepisode;
}

export interface Nextepisode {
  href: string;
}

export interface Externals {
  tvrage:  null;
  thetvdb: number;
  imdb:    null;
}

export interface Image {
  medium:   string;
  original: string;
}

export interface Rating {
  average: null;
}

export interface Schedule {
  time: string;
  days: any[];
}

export interface WebChannel {
  id:           number;
  name:         string;
  country:      Country;
  officialSite: string;
}

export interface Country {
  name:     string;
  code:     string;
  timezone: string;
}
